import {
  FETCH_CAT_REQUEST,
  FETCH_CAT_SUCCESS,
  FETCH_CAT_ERROR,
  fetchCatRequest,
  fetchCatSuccess,
  fetchCatError,
  fetchCat,
  ADOPT_CAT_REQUEST,
  ADOPT_CAT_SUCCESS,
  ADOPT_CAT_ERROR,
  adoptCatRequest,
  adoptCatSuccess,
  adoptCatError,
  adoptCat,
} from './cat';

import {
  FETCH_DOG_REQUEST,
  FETCH_DOG_SUCCESS,
  FETCH_DOG_ERROR,
  fetchDog,
  fetchDogRequest,
  fetchDogSuccess,
  fetchDogError,
  ADOPT_DOG_REQUEST,
  ADOPT_DOG_SUCCESS,
  ADOPT_DOG_ERROR,
  adoptDogRequest,
  adoptDogSuccess,
  adoptDogError,
  adoptDog
} from './dog';

export {
  FETCH_CAT_REQUEST,
  FETCH_CAT_SUCCESS,
  FETCH_CAT_ERROR,
  fetchCatRequest,
  fetchCatSuccess,
  fetchCatError,
  fetchCat,
  ADOPT_CAT_REQUEST,
  ADOPT_CAT_SUCCESS,
  ADOPT_CAT_ERROR,
  adoptCatRequest,
  adoptCatSuccess,
  adoptCatError,
  adoptCat,
  FETCH_DOG_REQUEST,
  FETCH_DOG_SUCCESS,
  FETCH_DOG_ERROR,
  fetchDog,
  fetchDogRequest,
  fetchDogSuccess,
  fetchDogError,
  ADOPT_DOG_REQUEST,
  ADOPT_DOG_SUCCESS,
  ADOPT_DOG_ERROR,
  adoptDogRequest,
  adoptDogSuccess,
  adoptDogError,
  adoptDog
}